services:
  caddy:
    environment:
      CADDY_ADMIN_PORT: 9019
    ports:
      - "9019:9019"
      - "9080:9080"
      - "9081:9081"
      - "9082:9082"
  elasticmq:
    ports:
      - "9324:9324"
  control-plane:
    environment:
      CADDY_ADMIN_URL: http://caddy:9019
