services:
  caddy:
    image: docker.io/library/caddy:2
    command: caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
    restart: unless-stopped
    volumes:
      - caddy-data:/data
      - caddy-config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile:ro

  control-plane:
    build: images/control-plane
    init: true
    working_dir: /app
    env_file: ${ENV_FILE:-development.env}
    environment:
      CONTAINER_HOST: unix:///run/podman.sock
      CONTAINER_HOST_ADDRESS: host.containers.internal
      CADDY_ADMIN_URL: http://caddy:2019
      CONTROL_PLANE_HOST: control-plane
    security_opt:
      - label=disable
    restart: unless-stopped
    volumes:
      - .:/app
      - node-modules:/app/node_modules
      - rockpool-data:/opt/rockpool
      - /var/run/docker.sock:/run/podman.sock
    depends_on:
      - caddy

volumes:
  caddy-data:
  caddy-config:
  rockpool-data:
  node-modules:
