services:
  caddy:
    ports:
      - "2019:2019"
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
  control-plane:
    environment:
      SPA_PROXY_URL: "http://control-plane:5173"
    command: node --watch --experimental-strip-types packages/server/src/index.ts
