module.exports = {
	apps: [
		{
			name: "test-elasticmq",
			script: "npm-scripts/setup-elasticmq.sh",
			args: "test",
			interpreter: "bash",
			autorestart: true,
			max_restarts: 3,
			restart_delay: 2000,
		},
		{
			name: "test-caddy",
			script: "caddy",
			args: "run",
			interpreter: "none",
			env: {
				CADDY_ADMIN: "localhost:9019",
			},
			autorestart: true,
			max_restarts: 3,
			restart_delay: 2000,
		},
		{
			name: "test-server",
			script: "packages/server/src/index.ts",
			interpreter: "node",
			interpreter_args: "--experimental-strip-types --env-file=test.env",
			autorestart: true,
			max_restarts: 10,
			restart_delay: 1000,
		},
		{
			name: "test-worker",
			script: "packages/worker/src/main.ts",
			interpreter: "node",
			interpreter_args: "--experimental-strip-types --env-file=test.env",
			autorestart: true,
			max_restarts: 10,
			restart_delay: 2000,
		},
		{
			name: "test-client",
			script: "npm",
			args: "run dev -w packages/client -- --port 9173",
			autorestart: true,
			max_restarts: 5,
			restart_delay: 1000,
		},
	],
};
